CC = gcc -Wall

clean:
	rm -f main

run:
	$(CC) main.c -o main
	@echo -e "\n"
	./main sender
	@echo -e "\n"
	./main date
	@echo -e "\n"
	./main abc@gmail.com Tytul afjwefoiashfuaseuoifhiuashefinm
	@echo -e "\n"
	make clean